//Authentication
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = "REGISTER_FAIL";

//Error
export const GET_ERRORS = "GET_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERROR";

//Notofications
export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

//Flow
export const UPDATE_FLOW = "UPDATE_FLOW";
export const INITIALIZE_FLOW = "INITIALIZE_FLOW";
export const LOAD_ALL_FLOWS = "LOAD_ALL_FLOWS";
export const LOAD_SELECTED_FLOWS = "LOAD_SELECTED_FLOWS";
export const NO_FLOWS = "NO_FLOWS";
export const DELETE_FLOW = "DELETE_FLOW";

//Email
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const INITIALIZE_EMAIL = "INITIALIZE_EMAIL";
export const LOAD_ALL_EMAILS = "LOAD_ALL_EMAILS";
export const LOAD_SELECTED_EMAIL = "LOAD_SELECTED_EMAIL";
export const NO_EMAILS = "NO_EMAILS";
export const DELETE_EMAIL = "DELETE_EMAIL";

//Campaigns
export const UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN";
export const INITIALIZE_CAMPAIGN = "INITIALIZE_CAMPAIGN";
export const LOAD_ALL_CAMPAIGNS = "LOAD_ALL_CAMPAIGNS";
export const LOAD_SELECTED_CAMPAIGN = "LOAD_SELECTED_CAMPAIGN";
export const NO_CAMPAIGNS = "NO_CAMPAIGNS";
export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
export const CHANGE_CAMPAIGN_CONFIG = "CHANGE_CAMPAIGN_CONFIG";